; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "玩机管家"
!define PRODUCT_VERSION "1.1.0"
!define PRODUCT_PUBLISHER "领创工作室"
!define PRODUCT_WEB_SITE "https://admt.lacs.cc"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\admt-lacs.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "..\src-tauri\icons\icon.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\admt-lacs.exe"
!define MUI_FINISHPAGE_SHOWREADME "$INSTDIR\admt-lacs.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\玩机管家"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "..\src-tauri\target\release\admt-lacs.exe"
  CreateDirectory "$SMPROGRAMS\玩机管家"
  CreateShortCut "$SMPROGRAMS\玩机管家\玩机管家.lnk" "$INSTDIR\admt-lacs.exe"
  CreateShortCut "$DESKTOP\玩机管家.lnk" "$INSTDIR\admt-lacs.exe"
  SetOutPath "$INSTDIR\adb"
  SetOverwrite try
  File "..\src-tauri\tools\adb\adb.exe"
  File "..\src-tauri\tools\adb\AdbWinApi.dll"
  File "..\src-tauri\tools\adb\AdbWinUsbApi.dll"
  File "..\src-tauri\tools\adb\fastboot.exe"
  SetOutPath "$INSTDIR\lacs"
  File "..\src-tauri\tools\lacs\readme.txt"
  File "..\src-tauri\tools\lacs\Usb_fix.bat"
  File "..\src-tauri\tools\lacs\Usb_Unfix.bat"
  File "..\src-tauri\tools\lacs\Usb_Verify.bat"
  SetOutPath "$INSTDIR"
  File "..\src-tauri\tools\README.md"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\玩机管家\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\玩机管家\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\admt-lacs.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\admt-lacs.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\README.md"
  Delete "$INSTDIR\lacs\Usb_Verify.bat"
  Delete "$INSTDIR\lacs\Usb_Unfix.bat"
  Delete "$INSTDIR\lacs\Usb_fix.bat"
  Delete "$INSTDIR\lacs\readme.txt"
  Delete "$INSTDIR\adb\fastboot.exe"
  Delete "$INSTDIR\adb\AdbWinUsbApi.dll"
  Delete "$INSTDIR\adb\AdbWinApi.dll"
  Delete "$INSTDIR\adb\adb.exe"
  Delete "$INSTDIR\admt-lacs.exe"

  Delete "$SMPROGRAMS\玩机管家\Uninstall.lnk"
  Delete "$SMPROGRAMS\玩机管家\Website.lnk"
  Delete "$DESKTOP\玩机管家.lnk"
  Delete "$SMPROGRAMS\玩机管家\玩机管家.lnk"

  RMDir "$SMPROGRAMS\玩机管家"
  RMDir "$INSTDIR\lacs"
  RMDir "$INSTDIR\adb"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd