; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "玩机管家"
!define PRODUCT_VERSION "1.2.0"
!define PRODUCT_PUBLISHER "领创工作室"
!define PRODUCT_WEB_SITE "https://admt.lacs.cc"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\admt-lacs.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "玩机管家"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\admt-lacs.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\玩机管家"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "src-tauri\target\release\admt-lacs.exe"
  SetOutPath "$INSTDIR\config"
  SetOverwrite try
  File "src-tauri\target\release\config\adbCommands.json"
  File "src-tauri\target\release\config\FastbootCommands.json"
  SetOutPath "$INSTDIR\tools\adb"
  File "src-tauri\target\release\tools\adb\adb.exe"
  File "src-tauri\target\release\tools\adb\AdbWinApi.dll"
  File "src-tauri\target\release\tools\adb\AdbWinUsbApi.dll"
  File "src-tauri\target\release\tools\adb\fastboot.exe"
  SetOutPath "$INSTDIR\tools\lacs"
  File "src-tauri\target\release\tools\lacs\readme.txt"
  File "src-tauri\target\release\tools\lacs\Usb_fix.bat"
  File "src-tauri\target\release\tools\lacs\Usb_Unfix.bat"
  File "src-tauri\target\release\tools\lacs\Usb_Verify.bat"
  SetOutPath "$INSTDIR\tools\scrcpy-win32-v3.3.1"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\adb.exe"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\AdbWinApi.dll"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\AdbWinUsbApi.dll"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\avcodec-61.dll"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\avformat-61.dll"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\avutil-59.dll"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\icon.png"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\libusb-1.0.dll"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\open_a_terminal_here.bat"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\scrcpy-console.bat"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\scrcpy-noconsole.vbs"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\scrcpy-server"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\scrcpy.exe"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\SDL2.dll"
  File "src-tauri\target\release\tools\scrcpy-win32-v3.3.1\swresample-5.dll"
  SetOutPath "$INSTDIR\resource\music"
  File "src-tauri\target\release\resource\music\error-08-206492.mp3"
  File "src-tauri\target\release\resource\music\notification-010-352755.mp3"
  File "src-tauri\target\release\resource\music\sucess_01.mp3"
  File "src-tauri\target\release\resource\music\warning-notification-call-184996.mp3"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\玩机管家.lnk" "$INSTDIR\admt-lacs.exe"
  CreateShortCut "$DESKTOP\玩机管家.lnk" "$INSTDIR\admt-lacs.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\admt-lacs.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\admt-lacs.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\resource\music\warning-notification-call-184996.mp3"
  Delete "$INSTDIR\resource\music\sucess_01.mp3"
  Delete "$INSTDIR\resource\music\notification-010-352755.mp3"
  Delete "$INSTDIR\resource\music\error-08-206492.mp3"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\swresample-5.dll"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\SDL2.dll"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\scrcpy.exe"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\scrcpy-server"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\scrcpy-noconsole.vbs"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\scrcpy-console.bat"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\open_a_terminal_here.bat"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\libusb-1.0.dll"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\icon.png"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\avutil-59.dll"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\avformat-61.dll"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\avcodec-61.dll"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\AdbWinUsbApi.dll"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\AdbWinApi.dll"
  Delete "$INSTDIR\tools\scrcpy-win32-v3.3.1\adb.exe"
  Delete "$INSTDIR\tools\lacs\Usb_Verify.bat"
  Delete "$INSTDIR\tools\lacs\Usb_Unfix.bat"
  Delete "$INSTDIR\tools\lacs\Usb_fix.bat"
  Delete "$INSTDIR\tools\lacs\readme.txt"
  Delete "$INSTDIR\tools\adb\fastboot.exe"
  Delete "$INSTDIR\tools\adb\AdbWinUsbApi.dll"
  Delete "$INSTDIR\tools\adb\AdbWinApi.dll"
  Delete "$INSTDIR\tools\adb\adb.exe"
  Delete "$INSTDIR\config\FastbootCommands.json"
  Delete "$INSTDIR\config\adbCommands.json"
  Delete "$INSTDIR\admt-lacs.exe"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\Website.lnk"
  Delete "$DESKTOP\玩机管家.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\玩机管家.lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR\tools\scrcpy-win32-v3.3.1"
  RMDir "$INSTDIR\tools\lacs"
  RMDir "$INSTDIR\tools\adb"
  RMDir "$INSTDIR\resource\music"
  RMDir "$INSTDIR\config"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd