import { makeStyles } from "@fluentui/react-components";

export const useAppStyles = makeStyles({
  app: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "var(--colorNeutralBackground1)",
    overflow: "hidden",
    background: "linear-gradient(135deg, var(--colorNeutralBackground1) 0%, var(--colorNeutralBackground2) 100%)",
  },
  startupFlowContainer: {
    position: "relative",
    height: "100vh",
    width: "100vw",
    overflow: "hidden",
  },
  transitionContainer: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    zIndex: 9999,
    pointerEvents: "none",
  },
  errorNotification: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "var(--colorNeutralBackground1)",
    background: "linear-gradient(135deg, var(--colorNeutralBackground1) 0%, var(--colorNeutralBackground2) 100%)",
  },
  errorHeader: {
    flex: "0 0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "48px 32px 24px",
  },
  errorHeaderContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
  },
  errorTitle: {
    fontSize: "28px",
    fontWeight: "600",
    color: "var(--colorPaletteRedForeground1)",
    textAlign: "center",
  },
  errorSubtitle: {
    fontSize: "16px",
    color: "var(--colorNeutralForeground2)",
    textAlign: "center",
  },
  errorBody: {
    flex: "1 1 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 32px",
  },
  errorContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "24px",
    padding: "48px",
    backgroundColor: "var(--colorNeutralBackground1)",
    borderRadius: "20px",
    boxShadow: "0 16px 64px rgba(0, 0, 0, 0.15)",
    border: "1px solid var(--colorNeutralStroke2)",
    maxWidth: "800px",
    width: "100%",
    minHeight: "300px",
  },
  errorMessage: {
    width: "100%",
    fontSize: "16px",
  },
  errorDetails: {
    backgroundColor: "var(--colorNeutralBackground2)",
    padding: "20px",
    borderRadius: "12px",
    width: "100%",
    border: "1px solid var(--colorNeutralStroke2)",
  },
  errorDetailsText: {
    fontSize: "14px",
    color: "var(--colorNeutralForeground2)",
    lineHeight: "1.5",
    textAlign: "center",
  },
  errorFooter: {
    flex: "0 0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 32px 48px",
  },
  countdownContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "12px",
    padding: "24px",
    backgroundColor: "var(--colorNeutralBackground2)",
    borderRadius: "16px",
    border: "1px solid var(--colorNeutralStroke2)",
  },
  countdownText: {
    color: "var(--colorNeutralForeground1)",
    fontSize: "16px",
    fontWeight: "500",
    textAlign: "center",
  },
  countdownNumber: {
    fontSize: "32px",
    fontWeight: "700",
    color: "var(--colorPaletteRedForeground1)",
    textAlign: "center",
    minWidth: "50px",
  }
});